'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { Terminal, CheckCircle, XCircle, ChevronDown, ChevronUp, Zap, BookOpen } from 'lucide-react';
import { useState } from 'react';
import type { PayloadResult } from '@/types';

interface PayloadsDisplayProps {
  payloads: PayloadResult[];
  applicableCount: number;
  totalCount: number;
}

function stripLlmPrefix(text: string): string {
  return text.replace(/^LLM\d+\s*[-–:]\s*/i, '').trim();
}

function PayloadBox({ text, index, label }: { text: string; index: number; label: string }) {
  return (
    <div>
      <p className="text-xs mb-1 font-medium" style={{ color: 'var(--color-text-muted)' }}>
        {label}
      </p>
      <div
        className="rounded-lg p-3 font-mono text-sm break-words whitespace-pre-wrap"
        style={{
          background: 'rgba(15,23,42,0.8)',
          border: '1px solid rgba(248,81,73,0.15)',
          color: '#fca5a5',
          lineHeight: 1.6,
        }}
      >
        {text}
      </div>
    </div>
  );
}

function PayloadCard({ payload, index }: { payload: PayloadResult; index: number }) {
  const [open, setOpen] = useState(true);
  const hasSpecific = payload.payloads.length > 0;
  const hasGeneric  = payload.generic_payloads.length > 0;
  const hasAny      = hasSpecific || hasGeneric;

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04, duration: 0.3 }}
      className="rounded-xl overflow-hidden"
      style={{
        background: hasAny ? 'rgba(248,81,73,0.05)' : 'rgba(88,166,255,0.04)',
        border: `1px solid ${hasAny ? 'rgba(248,81,73,0.2)' : 'rgba(88,166,255,0.12)'}`,
      }}
    >
      {/* Header */}
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-start gap-3 p-4 text-left hover:brightness-110 transition-all"
      >
        {hasAny ? (
          <CheckCircle className="w-4 h-4 mt-0.5 flex-shrink-0 text-red-400" />
        ) : (
          <XCircle className="w-4 h-4 mt-0.5 flex-shrink-0" style={{ color: '#58a6ff' }} />
        )}
        <div className="flex-1 min-w-0">
          <h4 className="text-sm font-semibold text-white">
            {stripLlmPrefix(payload.vulnerability_type)}
          </h4>
          <p className="text-xs mt-0.5" style={{ color: 'var(--color-text-muted)' }}>
            {payload.target_asset}
          </p>
        </div>
        {/* Counts */}
        <div className="flex items-center gap-2 flex-shrink-0 mt-0.5">
          {hasSpecific && (
            <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-medium"
                  style={{ background: 'rgba(248,81,73,0.15)', color: '#f85149' }}>
              <Zap className="w-3 h-3" />
              {payload.payloads.length} specific
            </span>
          )}
          {hasGeneric && (
            <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-medium"
                  style={{ background: 'rgba(167,139,250,0.15)', color: '#a78bfa' }}>
              <BookOpen className="w-3 h-3" />
              {payload.generic_payloads.length} generic
            </span>
          )}
          {!hasAny && (
            <span className="text-xs px-2 py-0.5 rounded-full font-medium"
                  style={{ background: 'rgba(88,166,255,0.1)', color: '#58a6ff' }}>
              N/A
            </span>
          )}
        </div>
        <div className="flex-shrink-0 ml-1" style={{ color: 'var(--color-text-muted)' }}>
          {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {/* Body */}
      <AnimatePresence initial={false}>
        {open && hasAny && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-4">

              {/* Specific payloads */}
              {hasSpecific && (
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <Zap className="w-3.5 h-3.5" style={{ color: '#f85149' }} />
                    <span className="text-xs font-semibold" style={{ color: '#f85149' }}>
                      Context-Specific Payloads
                    </span>
                    <span className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                      — generated by the redteam model for this agent
                    </span>
                  </div>
                  <div className="space-y-2">
                    {payload.payloads.map((p, i) => (
                      <PayloadBox key={i} text={p} index={i} label={`Payload ${i + 1}`} />
                    ))}
                  </div>
                </div>
              )}

              {/* Divider */}
              {hasSpecific && hasGeneric && (
                <div className="border-t" style={{ borderColor: 'var(--color-border)' }} />
              )}

              {/* Generic payloads */}
              {hasGeneric && (
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <BookOpen className="w-3.5 h-3.5" style={{ color: '#a78bfa' }} />
                    <span className="text-xs font-semibold" style={{ color: '#a78bfa' }}>
                      Generic Benchmark Payloads
                    </span>
                    <span className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                      — from the prompt injection benchmark dataset
                    </span>
                  </div>
                  <div className="space-y-2">
                    {payload.generic_payloads.map((p, i) => (
                      <PayloadBox key={i} text={p} index={i} label={`Generic ${i + 1}`} />
                    ))}
                  </div>
                </div>
              )}

            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function PayloadsDisplay({ payloads, applicableCount, totalCount }: PayloadsDisplayProps) {
  const withGeneric = payloads.filter(p => p.generic_payloads.length > 0).length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="glass-card p-5 mt-4"
      style={{ borderColor: 'rgba(248,81,73,0.3)' }}
    >
      {/* Header */}
      <div className="flex items-center gap-3 mb-4">
        <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
             style={{ background: 'rgba(248,81,73,0.1)' }}>
          <Terminal className="w-4 h-4" style={{ color: '#f85149' }} />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-white">Generated Attack Payloads</h3>
          <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
            <span style={{ color: '#f85149' }}>{applicableCount}</span> with specific payloads &nbsp;·&nbsp;
            <span style={{ color: '#a78bfa' }}>{withGeneric}</span> with generic payloads &nbsp;·&nbsp;
            {totalCount - applicableCount} not applicable
          </p>
        </div>
      </div>

      {/* Cards */}
      <div className="space-y-2">
        {payloads.map((p, i) => (
          <PayloadCard key={i} payload={p} index={i} />
        ))}
      </div>
    </motion.div>
  );
}
